config/routes.rb
Rails.application.routes.draw do
  resources :theses
  resources :talks
  resources :teachings
  resources :researches
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :protagonists
    get 'authors/new'
    get 'authors/destroy'
    #devise_for :users, controllers: { registration: 'registration' }
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    resource :users, only: [:edit] do
      #collection do
      patch 'update_password'
      #end
    end
    get 'welcome/index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :articles do
      resources :comments
      put 'addAuthor', on: :collection
      delete 'removeAuthor', on: :collection
      get 'listUsers', on: :collection
      delete 'removeUser', on: :collection
      put 'setRole', on: :collection
      delete 'removeRole', on: :collection
    end
    resources :authors
    resources :password_resets

      root 'articles#index'
      #  root 'welcome#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  translates  :content #, touch: true
  #has_rich_text :content
  has_one_attached :paper
  has_and_belongs_to_many :authors
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  scope :categorized, -> (category) {where("category LIKE ?", category)}
  scope :sorted_by_date, -> {order('date DESC')}
  delegate :content, to: :translation
  delegate :content=, to: :translation
  after_save do
    content.save if content_changed?
  end

  class Translation
    has_rich_text :content
  end

  def slug_candidates
    [:title,
     [:title, :category]
    ]
  end
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
  def author_names
    names = ''
    authors = self.authors
    len = authors.length
    if len == 1
      names = authors[0].name
    else
      authors.each_with_index  do |author, index|
        if index+1 == len
          names += 'and '
          names += author.name
        else
          names += author.name
          names += ', '
        end
      end
    end
     names
  end

  def self.save_all
    Article.all.each { |article| article.save! }
  end
end

app/models/author.rb
class Author < ApplicationRecord
  resourcify
  has_and_belongs_to_many :articles
  validates :name, presence: true
  def given_name
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  resourcify
  belongs_to :article
  validates :body, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
  actable
  translates :title , :description
end

app/models/protagonist.rb
class Protagonist < ApplicationRecord
  acts_as :user
  has_one_attached :avatar
end

app/models/research.rb
class Research < ApplicationRecord
  acts_as :detail
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/talk.rb
class Talk < ApplicationRecord
  acts_as :detail
end

app/models/teaching.rb
class Teaching < ApplicationRecord
  acts_as :detail
end

app/models/thesis.rb
class Thesis < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  actable
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #validates :actable_id, presence: false
  #validates :actable_type, presence: false
  def owner_of?(comment)
      if comment.commenter == self.name + "   " +self.lastName
        return true
      else
        return false
      end
  end

  def self.update_role(user_id, role_id,action)
    @user = User.find(user_id)
    @role = Role.find(role_id)
    if action.eql?("add")
      @user.add_role @role.name
    else
      @user.remove_role @role.name
    end
    @user.save!
  end

  def getRoles
    roles = ""
    self.roles.each do |role|
      roles += " " + role.name
    end
    roles
    end
=begin
  def self.set_roles
    @users = User.all
    admin = %w[fadjaarnaud@yahoo.fr zebazeprudy@yahoo.fr]
    protagonist = %w[arnaud.nguembafadja@unife.it ngmrnd@unife.it]
    @users.each do |user|
      if admin.include?(user.email)
        user.add_role :admin
        user.save!
      end

      if protagonist.include?(user.email)
        user.add_role :protagonist
        user.save!
      end
    end

    end
=end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #http_basic_authenticate_with name: "arnaud", password: "secret", except: [:index, :show]
  #before_action :set_article, only: [:show, :edit, :update, :new, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  def index
    @protagonist = Protagonist.all[0]
    #Article.save_all
    #Article.find_each(&:save)
    #User.set_roles
    #@journal_articles = Article.categorized("journal")
    #@chapter_articles = Article.categorized("chapter")
    #@conference_articles = Article.categorized("conference")
    #@workshop_articles = Article.categorized("workshop")

  end
  def show
    @article = Article.friendly.find(params[:id])
    #@article = Article.find(params[:id])
    #authorize @article
  end
  def new
    @article = Article.new
    authorize @article
  end

  def edit
    @article = Article.friendly.find(params[:id])
    authorize @article
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    authorize @article
    @article.paper.attach(params[:paper])
    
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

    def update
      @article = Article.friendly.find(params[:id])
      authorize @article
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

  def destroy
    @article = Article.friendly.find(params[:id])
    authorize @article
    @article.paper.purge
    @article.destroy
    redirect_to articles_path
  end

  def addAuthor
    @article = Article.find(params[:article][:article_id])
    authorize @article
    @author = Author.find(params[:article][:author_id])
    if not @article.authors.exists?(params[:article][:author_id])
        @article.authors << @author
    end
    #@article.authors << @author
    #render plain: @author.inspect
    #render plain: @article.inspect
    #render plain: params[:article].inspect
    #render 'index'
    redirect_to articles_path
  end

  def removeAuthor
    @article = Article.find(params[:article][:article_id])
    authorize @article
    @author = Author.find(params[:article][:author_id])
    @article.authors.delete(@author)
      #render plain: @author.inspect
    #render plain: @article.inspect
    #render plain: params[:article].inspect
    redirect_to articles_path
      #render 'index'
  end
  def listUsers
    @users = User.all
  end

  def removeUser
    #@user = User.find(params[:user][:user_id])
    @user = User.find(params[:user_id])
    #authorize @user
    @user.destroy
    redirect_to listUsers_articles_path
  end

  def setRole
    User.update_role(params[:role][:user_id], params[:role][:role_id], "add")
    redirect_to listUsers_articles_path
  end

  def removeRole
    User.update_role(params[:role][:user_id], params[:role][:role_id], "remove")
    redirect_to listUsers_articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :category,  :content, :date, :conferenceName, :paper, :paperUrl)
  end
end

# <!-- 
#       <% if article.paper.attached? %>
#         <%= link_to( "[.pdf]", article.paper, class:"text-danger") %>
#       <%end %>
#       -->

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/protagonists_helper.rb
module ProtagonistsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_adminManagement.html.erb
<% if current_user and current_user.has_any_role? :admin, :protagonist %>

  <%= link_to edit_article_path(article), { class: 'tooltips, text-warning', 'data-bs-toggle' => 'tooltip', 'data-placement' => 'top', :title => '', 'data-original-title' => "#{t 'articles._listArticle.editMessage'}" } do %>
      <i class="fa fa-edit"></i>
      <%end %>
    <% if policy(article).destroy? %>

  <%= link_to article_path(article), { class: 'tooltips, text-danger', 'data-bs-toggle' => 'tooltip', 'data-placement' => 'top', :title => '', 'data-original-title' => "#{t 'articles._listArticle.destroyMessage'}", method: :delete, data: {confirm: "#{t 'global.confirmDelete'}" }} do %>
        <i class="fa fa-trash" aria-hidden="true" ></i>
        <%end %>
    <%end %>
  <%= form_with model: article, :url => "/articles/addAuthor", method: "PUT", local: true do |f|  %>
    <%= f.collection_select(:author_id, Author.all, :id, :name, options = {prompt: 'Add an author'}, html_options = {class: "custom-select-sm"}) %>
    <%= f.hidden_field :article_id, value: article.id %>
    <%= f.submit "Add author" %>
  <%end %>


  <%= form_with model: article, :url => "/articles/removeAuthor", method: "delete",data: {confirm: "#{t 'global.confirmDelete'}"}, local: true do |f|  %>
    <%= f.collection_select(:author_id, article.authors, :id, :name, options = {prompt: 'Remove an author'}, html_options = {class: "custom-select-sm"}) %>
    <%= f.hidden_field :article_id, value: article.id %>
    <%= f.submit "Remove author" %>
  <%end %>
<%end %>

app/views/articles/_details.html.erb
<p>
  <strong> <%= label(:article, :title)%>:</strong>
  <%= @article.title %>
</p>

<p>
  <strong> <%= label(:article, :text)%>:</strong>
  <%= @article.text %>
</p>

<p>
  <strong> <%= label(:article, :description) %>:</strong>
  <%= @article.content %>
</p>

<!-- 
<p>
  <strong> <%= label(:article, :category) %>:</strong>
  <%= @article.category %>
</p>
-->

<p>
  <strong> <%= t 'global.publishedAt' %>:</strong>
  <%= @article.conferenceName %>
</p>

<p>
  <strong><%=t 'global.download' %>: </strong>
  <%= link_to( "[.pdf]", @article.paperUrl, class:"text-danger") %>
  <!--
  <% if @article.paper.attached? %>
    <%= link_to( "[.pdf]", @article.paper, class:"text-danger") %>
  <%end %>
  -->
</p>

app/views/articles/_drawRow.html.erb
<div class='row'>
  <div class='col-lg-10 col-lg-offset-2' >
    <hr style="border-top: 4px solid #39abac">
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, rows: "5", class: "w-25 p-3"%>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.rich_text_area :content , rows: "5", class: "w-50 p-3" %>
  </p>

  <p>
    <%= f.label :conferenceName %><br>
    <%= f.text_field :conferenceName %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
   
   <p>
    <%= f.label :paperUrl %><br>
    <%= f.text_field :paperUrl %>
  </p>

   <!-- 
      <p>
    <%= f.label "Paper" %><br>
    <%= f.file_field :paper %>
    </p>
  -->
  

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/_listArticle.html.erb
<ol class="list-group">
  <% len = @articles.length%>
  <% @articles.each_with_index do |article, index| %>

    <li class ="list-group-item"> &nbsp;&nbsp;&nbsp;
      <span class="badge badge-secondary badge-danger"><%=index +1%></span>  &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
      <%= article.author_names %>. <span class="font-weight-bold"> <%= article.title %>. </span> <%= article.text %>
      <%= link_to( "[.pdf]", article.paperUrl, class:"text-danger") %>
      
      <%= link_to  article_path(article), { class: 'tooltips, text-info', 'data-bs-toggle' => 'tooltip', 'data-placement' => 'top', :title => '', 'data-original-title' => "#{t 'articles._listArticle.detailsMessage'}" } do %>
          <i class="fa fa-info" aria-hidden="true"></i>
        <%end %> 

      <!-- <% if user_signed_in? and policy(article).show? %>  article_path(article) -->
        
      <!--<%end %> -->
      <%= render partial: 'adminManagement',  locals: {article: article} %>
    </li>
    <% unless index+1 == len %>
    <div class='row'>
      <div class='col-lg-10 col-lg-offset-2'>
        &nbsp;&nbsp;
      </div>
    </div>
      <%end %>
  <% end %>
</ol>

app/views/articles/_navbarForm.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top nav-tabs nav-pills " role="navigation">
  <div class="container">
    <!--<a class="navbar-brand" href="#">Brand</a> -->
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <div class="collapse navbar-collapse" id="exCollapsingNavbar">
      <ul class="nav navbar-nav">
        <li class="nav-item active"><%= link_to 'Home1', articles_path, class: "nav-link" %></li>
        <li class="nav-item"><a href="#" class="nav-link">About me1 </a></li>
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Projects</a>
            <div class="dropdown-menu">
              <a class="dropdown-item text-uppercase" href="#">MACHINE LEARNING @ UNIFE</a>
              <a class="dropdown-item text-uppercase" href="#">SYSTEM AFRIK INFORMATION TECHNOLOGY</a>
              <a class="dropdown-item text-uppercase " href="#">After school</a>

            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Courses</a>
            <div class="dropdown-menu">
              <a class="dropdown-item text-uppercase" href="#">Programming language</a>
              <a class="dropdown-item text-uppercase" href="#">Deep learning</a>
            </div>
          </li>
        <%end %>
        <!-- <li class="nav-item"><a href="#" class="nav-link">More</a></li> -->
      </ul>
      <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
        <!-- <li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i class="fa fa-cog fa-fw fa-lg"></i></a></li> -->

        <%if current_user %>
          <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Edit profile', edit_user_registration_path , class: "nav-link" %></li>
          <li class="nav-item text-success"> Welcome  <%= current_user.name%> </li>
          <!-- Navbar text  <span class="navbar-text text-success"> Welcome <%= current_user.name%></span>-->


        <% else %>
          <li class="nav-item"><%= link_to 'Register', new_user_registration_path , class: "nav-link", kind: "new"  %></li>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path , class: "nav-link"%></li>
        <%end %>
      </ul>
    </div>
  </div>
</nav>

<%= render 'layouts/alert' %>

app/views/articles/_protagonistsInfo.html.erb
<div class ="info">
  <h1>
   Dr <%=@protagonist.name  %>
    <%=@protagonist.lastName  %>
  </h1>
<p>
  <br> <br>
<%=t 'activerecord.attributes.protagonist.profession' %>: <%=@protagonist.profession %>
</p>

<p >
  <%=@protagonist.department %>,  <%= link_to @protagonist.university, "http://www.unife.it", class: "text-danger" %>
</p>

<p>
  <%=@protagonist.edifice %>
</p>

<p>
  <%=@protagonist.university %>
</p>

<p>
  <%=@protagonist.workAddress %>
</p>

<p>
 Tel: <%=@protagonist.workPhone %>  Fax: <%=@protagonist.workPhone %>

</p>

  <p>
    E-Mail: <%=mail_to(@protagonist.email, name = nil, html_options = {class: "text-danger"}) %>
  </p>

<p>
  <%=@protagonist.university %>
</p>
</div>

app/views/articles/_test.html.erb
<footer class="site-footer" id="site-footer">
  <div class="hfg_footer">
    <div class="footer--row footer-bottom layout-full-contained"
         id="cb-row--footer-bottom"
         data-row-id="bottom" data-show-on="desktop">
      <div
        class="footer--row-inner footer-bottom-inner dark-mode footer-content-wrap">
        <div class="container">
          <div
            class="hfg-grid nv-footer-content hfg-grid-bottom row--wrapper row "
            data-section="hfg_footer_layout_bottom" >
            <div class="builder-item hfg-item-first col-4 col-md-4 col-sm-4 hfg-item-center offset-1"><div class="item--inner builder-item--footer-one-widgets"
                                                                                                           data-section="sidebar-widgets-footer-one-widgets"
                                                                                                           data-item-id="footer-one-widgets">
              <div class="widget-area">
                <div id="custom_html-3" class="widget_text widget widget_custom_html"><div class="textwidget custom-html-widget"><img src="http://ml.unife.it/wp-content/uploads/2019/11/1.png" width=40 alt="img">
                  <p class="footer-text">
                    Università di Ferrara
                    <br><br>
                    DE - Department of Engineering<br>
                    Via Saragat, 1 - 44122 Ferrara, Italy
                    <br><br>
                    DMI - Department of Mathematics and Computer Science<br>
                    Via Machiavelli, 30 - 44121 Ferrara, Italy

                  </p></div></div>	</div>
            </div>

            </div><div class="builder-item col-2 col-md-2 col-sm-2 hfg-item-center"><div class="item--inner builder-item--footer-two-widgets"
                                                                                         data-section="sidebar-widgets-footer-two-widgets"
                                                                                         data-item-id="footer-two-widgets">
            <div class="widget-area">
              <div id="custom_html-4" class="widget_text widget widget_custom_html"><div class="textwidget custom-html-widget"><img src="http://ml.unife.it/wp-content/uploads/2019/11/2.png" width=40 style="margin-top:-2px">
                <p class="footer-text">	ml@unife.it
                </p></div></div>	</div>
          </div>

          </div><div class="builder-item hfg-item-last col-4 col-md-4 col-sm-4 hfg-item-center offset-1"><div class="item--inner builder-item--footer-three-widgets"
                                                                                                              data-section="sidebar-widgets-footer-three-widgets"
                                                                                                              data-item-id="footer-three-widgets">
            <div class="widget-area">
              <div id="custom_html-5" class="widget_text widget widget_custom_html"><div class="textwidget custom-html-widget"><p class="footer-text rectangle" style="padding-top:15px">
                ML Group - Università di Ferrara<br>
                © 2018 ML@UniFE. All rights reserved
              </p></div></div>	</div>
          </div>

          </div>							</div>
        </div>
      </div>
    </div>

  </div>
</footer>

app/views/articles/edit.html.erb
<div class="container">
<h1>Edit Article</h1>
<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="articles" id="art">
<div>
  <!-- <%=link_to "reset your password", edit_user_password_url(reset_password_token: @token), html_options = { style: "font-weight: bold" } %> -->
  <%if current_user %>
    <% if current_user.has_any_role? :admin, :protagonist %>

      <%= link_to 'Change Password', "/users/update_password" %>
      <%= link_to 'New article', new_article_path %>
      <%= link_to 'New author', new_author_path %>
      <% if current_user.has_role? :admin %>
      <%= link_to 'New protagonist', new_protagonist_path %>
        <%= link_to "List users", listUsers_articles_path %>
      <%end %>
      <% unless @protagonist.nil?  %>
          <%= link_to 'Edit protagonist', edit_protagonist_path(@protagonist) %>

        <% if current_user.has_role? :admin %>
          <%= link_to 'Destroy protagonist', protagonist_path(@protagonist), method: :delete, data: {confirm: "#{t 'global.confirmDelete'}"}%>
        <%end %>
      <%end %>
    <%end %>

    <%end %>
</div>
  <% unless @protagonist.nil?  %>
<div class="d-flex title-paper">
  <div>
    <%= render partial: 'protagonistsInfo',  locals: {protagonist: @protagonist} %>
  </div>
  <div class="mx-auto d-block media ">
    <p>
      <% if @protagonist.avatar.attached? %>
        <%= image_tag("Arnaud.png", alt: "Dr Arnaud Nguembang Fadja", width: "300px") %>
      <%end %>
    </p>
    
  </div>
</div>
    <%end %>
    <!-- image_tag(@protagonist.avatar,size: '300')  --> 
<div class='row'>
  <div class='col-lg-12 col-lg-offset-2' >
    <hr class="line">
  </div>
</div>
  <h2 id ="title", class="display-3"> <%= t '.publications' %></h2>
  <h2 class="title-paper"><%= t '.journals' %></h2>
<% @articles = Article.categorized("journal").sorted_by_date %>
<%= render partial: 'listArticle',  locals: {articles: @articles} %>

<h2 class="title-paper"><%= t '.chapters' %></h2>
<% @articles = Article.categorized("chapter").sorted_by_date %>
<%= render partial: 'listArticle',  locals: {articles: @articles} %>

<h2 class="title-paper"><%= t '.conferences' %></h2>
<% @articles = Article.categorized("conference").sorted_by_date %>
<%= render partial: 'listArticle',  locals: {articles: @articles} %>

<h2 class="title-paper"><%= t '.workshops' %></h2>
<% @articles = Article.categorized("workshop").sorted_by_date %>
<%= render partial: 'listArticle',  locals: {articles: @articles} %>
</div>

app/views/articles/listUsers.html.erb
<ol class="list-group">
  <% len = @users.length%>
  <% @users.each_with_index do |user, index| %>

    <li class ="list-group-item"> &nbsp;&nbsp;&nbsp;
      <span class="badge badge-secondary badge-danger"><%=index +1%></span>  &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
      <p> Name: <%= "#{user.name} #{user.lastName}" %>.  </p>
      <p>Email: <span class="font-weight-bold"> <%= user.email %>. </span></p>
      <p>Roles: <%= user.getRoles %></p>
      <p>
      <%= form_with model: Role.all[0], :url => "/articles/setRole", method: "PUT", local: true do |f|  %>
        <%= f.collection_select(:role_id, Role.all, :id, :name, options = {prompt: 'select a role'}, html_options = {class: "custom-select-sm"}) %>
        <%= f.hidden_field :user_id, value: user.id %>
        <%= f.submit "Add Role" %>
      <%end %>
      </p>

      <p>
        <%= form_with model: Role.all[0], :url => "/articles/removeRole", method: "delete",data: {confirm: "#{t 'global.confirmDelete'}"}, local: true do |f|  %>
          <%= f.collection_select(:role_id, Role.all, :id, :name, options = {prompt: 'select a role'}, html_options = {class: "custom-select-sm"}) %>
          <%= f.hidden_field :user_id, value: user.id %>
          <%= f.submit "Remove Role" %>
        <%end %>
      </p>

      <%= link_to removeUser_articles_path(user_id: user.id ), { class: 'tooltips, text-danger', 'data-bs-toggle' => 'tooltip', 'data-placement' => 'top', :title => '', 'data-original-title' => "#{t 'users.destroyMessage'}", method: :delete, data: {confirm: "#{t 'global.confirmDelete'}" }} do %>
        <i class="fa fa-trash" aria-hidden="true" ></i>
      <%end %>

      <!--
      <%= link_to "Delete", removeUser_articles_path(:user_id =>  user.id ), method: :delete, data: {confirm: "#{t 'global.confirmDelete'}", user_id: user.id }%>
      -->
      <!--
      <%= form_with model: user, :url => "/articles/removeUser", method: "delete",data: {confirm: "#{t 'global.confirmDelete'}"}, local: true do |f|  %>
        <%= f.hidden_field :user_id, value: user.id %>
        <%= f.submit "Remove User" %>
        <%end %>
      -->

    </li>

  <% end %>
</ol>

app/views/articles/new.html.erb
<div class="container">
<h1>New Article</h1>

<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h3 class="text-center  pt-4 display-3 text-info"><%= t 'articles._listArticle.detailsTitle' %></h3>

<div class="container p-3  my-3 border ">

  <%= render 'details',  locals: {article: @article} %>

<h2><%= t 'global.comment' %></h2>
<%= render @article.comments %>

<% if current_user %>
<%= render 'comments/form' %>
<%end %>
</div>