config/routes.rb
Rails.application.routes.draw do
  resources :theses
  resources :talks
  resources :teachings
  resources :researches
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :protagonists
    get 'authors/new'
    get 'authors/destroy'
    #devise_for :users, controllers: { registration: 'registration' }
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    resource :users, only: [:edit] do
      #collection do
      patch 'update_password'
      #end
    end
    get 'welcome/index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :articles do
      resources :comments
      put 'addAuthor', on: :collection
      delete 'removeAuthor', on: :collection
      get 'listUsers', on: :collection
      delete 'removeUser', on: :collection
      put 'setRole', on: :collection
      delete 'removeRole', on: :collection
    end
    resources :authors
    resources :password_resets

      root 'articles#index'
      #  root 'welcome#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  translates  :content #, touch: true
  #has_rich_text :content
  has_one_attached :paper
  has_and_belongs_to_many :authors
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  scope :categorized, -> (category) {where("category LIKE ?", category)}
  scope :sorted_by_date, -> {order('date DESC')}
  delegate :content, to: :translation
  delegate :content=, to: :translation
  after_save do
    content.save if content_changed?
  end

  class Translation
    has_rich_text :content
  end

  def slug_candidates
    [:title,
     [:title, :category]
    ]
  end
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
  def author_names
    names = ''
    authors = self.authors
    len = authors.length
    if len == 1
      names = authors[0].name
    else
      authors.each_with_index  do |author, index|
        if index+1 == len
          names += 'and '
          names += author.name
        else
          names += author.name
          names += ', '
        end
      end
    end
     names
  end

  def self.save_all
    Article.all.each { |article| article.save! }
  end
end

app/models/author.rb
class Author < ApplicationRecord
  resourcify
  has_and_belongs_to_many :articles
  validates :name, presence: true
  def given_name
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  resourcify
  belongs_to :article
  validates :body, presence: true
end

app/models/detail.rb
class Detail < ApplicationRecord
  actable
  translates :title , :description
end

app/models/protagonist.rb
class Protagonist < ApplicationRecord
  acts_as :user
  has_one_attached :avatar
end

app/models/research.rb
class Research < ApplicationRecord
  acts_as :detail
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/talk.rb
class Talk < ApplicationRecord
  acts_as :detail
end

app/models/teaching.rb
class Teaching < ApplicationRecord
  acts_as :detail
end

app/models/thesis.rb
class Thesis < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  actable
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #validates :actable_id, presence: false
  #validates :actable_type, presence: false
  def owner_of?(comment)
      if comment.commenter == self.name + "   " +self.lastName
        return true
      else
        return false
      end
  end

  def self.update_role(user_id, role_id,action)
    @user = User.find(user_id)
    @role = Role.find(role_id)
    if action.eql?("add")
      @user.add_role @role.name
    else
      @user.remove_role @role.name
    end
    @user.save!
  end

  def getRoles
    roles = ""
    self.roles.each do |role|
      roles += " " + role.name
    end
    roles
    end
=begin
  def self.set_roles
    @users = User.all
    admin = %w[fadjaarnaud@yahoo.fr zebazeprudy@yahoo.fr]
    protagonist = %w[arnaud.nguembafadja@unife.it ngmrnd@unife.it]
    @users.each do |user|
      if admin.include?(user.email)
        user.add_role :admin
        user.save!
      end

      if protagonist.include?(user.email)
        user.add_role :protagonist
        user.save!
      end
    end

    end
=end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: %i[ show edit update destroy ]

  # GET /talks or /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1 or /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks or /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to talk_url(@talk), notice: "Talk was successfully created." }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1 or /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to talk_url(@talk), notice: "Talk was successfully updated." }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1 or /talks/1.json
  def destroy
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to talks_url, notice: "Talk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def talk_params
      params.require(:talk).permit(:title, :description, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/protagonists_helper.rb
module ProtagonistsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/talks/_form.html.erb
<%= form_with(model: talk, local: true) do |form| %>
  <% if talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
        <% talk.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing Talk</h1>

<%= render 'form', talk: @talk %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<!--
<p id="notice"><%= notice %></p>

<h1>Talks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.title %></td>
        <td><%= talk.description %></td>
        <td><%= talk.year %></td>
        <td><%= link_to 'Show', talk %></td>
        <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
        <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

-->
<div class="message-container">
  <h2>TO BE DONE</h2>
</div>

app/views/talks/new.html.erb
<h1>New Talk</h1>

<%= render 'form', talk: @talk %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @talk.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @talk.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @talk.year %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>